### ISSUE TITLE
bin 解析错误哦

### ISSUE THREAD

**Issue by chasinghope** [focus-creative-games/luban_unity#1]
![QQ图片20240229142424](https://github.com/focus-creative-games/luban_unity/assets/42870306/0ca1c55b-f0d9-49c0-ba6b-96d8e8f5ccb3)
配置如上，这样配置走json是好的，走bin报错
![QQ图片20240229142433](https://github.com/focus-creative-games/luban_unity/assets/42870306/82bc8383-e8c5-4897-8361-dfec6ad12db8)
![QQ图片20240229142448](https://github.com/focus-creative-games/luban_unity/assets/42870306/42b2bf73-47aa-4664-b00f-6dc2d2574e81)

**Comment by pirunxi** [comment]
不太应该吧，你确定吗，会不会搞错输入文件了? bin这种格式已经稳定运行很多年了。如果确实有问题，提供一个复现工程给我们。
