### ISSUE TITLE
StringUtil.CollectionToString 拼写错误

### ISSUE THREAD

**Issue by DengWang** [focus-creative-games/luban_unity#2]
StringUtil.CollectionToString 拼写错误, 应该为 var sb = new StringBuilder("{"); 使用双引号,不然会当成整形处理

**Comment by pirunxi** [comment]
我们在2019及各个版本测试了，没发现问题，请给一个例子，是怎么出错的。

**Comment by DengWang** [comment]
![image](https://github.com/user-attachments/assets/631883e3-2004-4f37-9490-a5d5987ff9a3)
这个大括号被当作capacity
![image](https://github.com/user-attachments/assets/7a4bae58-b41e-469c-8b20-e6524a884cd5)

**Comment by pirunxi** [comment]
我们确认了这个问题，已经在v1.1.1版本修复。非常非常感谢。这个居然是一直以来都存在的bug！
