### ISSUE TITLE
I want to edit value of variables that was generated by Luban

### ISSUE THREAD

**Issue by SangTVArcherGame** [focus-creative-games/luban_unity#3]
Thanks for your great tool,
I create C# class by your tool, but I don't find any way to make it is writable variable. Does the tool help that?

**Comment by pirunxi** [comment]
The generated code is used in runtime,  so it should not be mutable. if you want to use hybridclr in editor and use it to load and save json file, you can try cs-editor-json. This is a [demo](https://github.com/focus-creative-games/luban_examples/blob/main/Projects/Csharp_Unity_Editor_json/gen.bat)
